apiVersion: v1
kind: ServiceAccount
metadata:
  name: audit-collector
  namespace: audit-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: audit-collector
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/log"]
    verbs: ["get", "list"]
  - apiGroups: ["security.openshift.io"]
    resourceNames: ["privileged"]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: audit-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: audit-collector
subjects:
  - kind: ServiceAccount
    name: audit-collector
    namespace: audit-system
